---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "41"
year: "2022"
contributor: 
- "Karsten Schuldt"
title: "Minitel, Btx und die Bibliotheken. Ein Versuch, den Zusammenhang von neuen Technologien und Bibliotheken zu systematisieren"
abstract: "Anhand der vor allem in den 1980er Jahren verbreiteten Technologie der interaktiven Videotextsysteme und den daraus resultierenden Reaktionen von Bibliotheken, wird versucht, ein Modell für den Zusammenhang von Bibliotheken und neuen Technologien zu erarbeiten. Konzentriert wird sich dabei auf das französische Minitel- und das bundesdeutsche Btx-System. Im Ergebnis zeigt sich, dass Bibliotheken relativ schnell reagieren, neue Technologien daraufhin zu hinterfragen, ob sie für Aufgaben in Bibliotheken genutzt werden können. Es zeigt sich aber auch, dass die tatsächliche Verbreitung in Bibliotheken massiv von Entwicklungen ausserhalb von Bibliotheken beeinflusst wird. Der Artikel endet mit ersten Eckpunkten für ein solches Modell und offenen Forschungsfragen."
abstractalt: "Using the technology of interactive videotex systems, which became widespread especially in the 1980s, and the reaction of libraries towards these technologies as an example, an attempt was made to develop a model for the relationship between libraries and new technologies. The focus is on the French Minitel- and the German Btx-system. Results show that libraries react relatively quickly when they question new technologies as to whether they can be used for tasks in libraries themselves. But also that the actual dissemination is massively influenced by developments outside of libraries themselves. The article ends with first sketches for such a model and open research questions."
pdf: "main.pdf"
date: 2022-06-03
comments: false
sharing: true
footer: true

---
