---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "41"
year: "2022"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #41: Big Scholarly Data"
pdf: "https://doi.org/10.18452/24796"
doi: "10.18452/24796"
date: 2022-06-13
comments: false
sharing: true
footer: true

---