---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "41"
year: "2022"
contributor: 
- "Philipp Zumstein"
title: "Blitzschnelles Publizieren mit Academia Letters, aber sag', wie verhält es sich mit der Qualitätssicherung? Ein informationswissenschaftlicher Kommentar"
pdf: "https://doi.org/10.18452/24799"
doi: "10.18452/24799"
date: 2022-06-02
comments: false
sharing: true
footer: true

---