---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "41"
year: "2022"
contributor: 
- "Nick Haupka"
- "Najko Jahn"
- "Anne Hobert"
title: "Praxisbericht Big Scholarly Data an der SUB Göttingen"
abstract: "Der Beitrag stellt den Einsatz des kommerziellen Cloud-Computing-Dienstes Google BigQuery für die Arbeit mit großen offenen Datensätzen über wissenschaftliche Veröffentlichungen an der Nidersächsischen Staats- und Universitätsbibliothek Göttingen (SUB Göttingen) vor, insbesondere bezogen auf den Datenbestand, die Prozessierung und die Zugriffsmöglichkeiten. Als beispielhafter Use Case werden überregionale Open-Access-Transformationsverträgen in Deutschland bezogen auf ihren Open-Access-Anteil analysiert."
pdf: "main.pdf"
date: 2022-06-02
comments: false
sharing: true
footer: true

---