---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "41"
year: "2022"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #10 (Frühling / Sommer 2022)"
pdf: "main.pdf"
doi: ""
date: 2022-06-04
comments: false
sharing: true
footer: true

---